### ISSUE TITLE
📋 Open source checklist

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-hydra#3]
In order to prep this repository for open source use and consumption, we need to complete this checklist:

## Repository checklist
- [ ] Add `.github` directory with pull request template, issue template(s) (1 template for bugs, 1 template for features)
- [ ] Add Reaction's standard `LICENSE.md`
- [ ] Add Reaction's standard `CODE_OF_CONDUCT.md`
- [ ] Add Reaction's standard `CONTRIBUTING.md`

## README checklist
- [ ] Add a screenshot, if applicable
- [ ] Add and check install instructions
- [ ] Add requirements list
- [ ] Add link back to reactioncommerce.com, Reaction repo, Reaction docs, and other related Reaction tools/repos
- [ ] Make it clear in the README whether this repository is open to new features, or whether new feature requests should go into: https://github.com/reactioncommerce/reaction-feature-requests
- [ ] Make it clear in the README what the development status of this project is
